package me.fengorz.kiwi.common.ytb;

import org.junit.jupiter.api.Assertions;
import org.junit.jupiter.api.Test;

import java.io.File;
import java.io.IOException;
import java.net.URL;
import java.net.URLDecoder;
import java.nio.charset.StandardCharsets;
import java.util.List;

public class SubtitleExtractorTest {

    @Test
    public void testAnalyze_MessyFile() throws IOException {
        File file = getFile("ChatGPT Atlas, OpenAI’s new web browser.en.vtt");
        SubtitleExtractor extractor = new SubtitleExtractor();
        SubtitleExtractor.SubtitleAnalysisResult result = extractor.analyze(file);

        Assertions.assertTrue(result.isAutoGenerated(), "Should be detected as auto-generated");
        List<String> subtitles = result.getSubtitles();

        Assertions.assertFalse(subtitles.isEmpty());

        // Check for specific known duplicate line
        // In the raw file, "What's your predictions? Do you think" appears multiple
        // times.
        // We expect it to appear exactly once in the output (excluding timestamps).
        long count = subtitles.stream()
                .filter(s -> s.equals("What's your predictions? Do you think"))
                .count();
        Assertions.assertEquals(1, count,
                "Should have exactly one occurrence of the line 'What's your predictions? Do you think'");

        // Check that we don't have orphan timestamps (timestamps followed by another
        // timestamp)
        // This is harder to check without strict regex, but we can check that we don't
        // have consecutive timestamp lines
        for (int i = 0; i < subtitles.size() - 1; i++) {
            boolean isCurrentTimestamp = isTimestamp(subtitles.get(i));
            boolean isNextTimestamp = isTimestamp(subtitles.get(i + 1));
            Assertions.assertFalse(isCurrentTimestamp && isNextTimestamp,
                    "Should not have consecutive timestamps: " + subtitles.get(i) + " and " + subtitles.get(i + 1));
        }
    }

    @Test
    public void testAnalyze_GoodFile() throws IOException {
        File file = getFile("ChatGPT Atlas, OpenAI’s new web browser.en-US.vtt");
        SubtitleExtractor extractor = new SubtitleExtractor();
        SubtitleExtractor.SubtitleAnalysisResult result = extractor.analyze(file);

        Assertions.assertFalse(result.isAutoGenerated(), "Should NOT be detected as auto-generated");
        List<String> subtitles = result.getSubtitles();

        Assertions.assertFalse(subtitles.isEmpty());

        // Verify content
        long count = subtitles.stream()
                .filter(s -> s.contains("What's your prediction? Do you think"))
                .count();
        Assertions.assertEquals(1, count, "Should contain the line 'What's your prediction? Do you think'");
    }

    private File getFile(String name) throws IOException {
        URL url = this.getClass().getClassLoader().getResource(name);
        if (url == null) {
            throw new RuntimeException("File not found: " + name);
        }
        // Decode URL to handle spaces and special characters
        return new File(URLDecoder.decode(url.getFile(), StandardCharsets.UTF_8.name()));
    }

    private boolean isTimestamp(String line) {
        return line.matches("\\d{2}:\\d{2}:\\d{2}\\.\\d{3}\\s+-->\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d{3}.*");
    }
}
