/*
 *
 * Copyright [2019~2025] [codingByFeng]
 *
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except in compliance with
 * the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License is distributed on
 * an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the License for the
 * specific language governing permissions and limitations under the License.
 *
 *
 */

package me.fengorz.kiwi.common.tts.service.impl;

import com.baidu.aip.speech.AipSpeech;
import com.baidu.aip.speech.TtsResponse;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import me.fengorz.kiwi.common.sdk.exception.tts.TtsException;
import me.fengorz.kiwi.common.sdk.util.validate.KiwiAssertUtils;
import me.fengorz.kiwi.common.tts.TtsConstants;
import me.fengorz.kiwi.common.tts.enumeration.TtsSourceEnum;
import me.fengorz.kiwi.common.tts.model.BaiduTtsProperties;
import me.fengorz.kiwi.common.tts.service.BaiduTtsService;
import org.springframework.core.Ordered;
import org.springframework.core.annotation.Order;
import org.springframework.stereotype.Service;

import java.util.HashMap;

import static me.fengorz.kiwi.common.tts.TtsConstants.BEAN_NAMES.BAIDU_TTS_SERVICE_IMPL;

/**
 * @Description TODO
 * @Author Kason Zhan
 * @Date 2022/10/1 11:20
 */
@Slf4j
@Service(BAIDU_TTS_SERVICE_IMPL)
@Order(Ordered.HIGHEST_PRECEDENCE)
@RequiredArgsConstructor
public class BaiduTtsServiceImpl implements BaiduTtsService {

    private final BaiduTtsProperties config;

    @Override
    public byte[] speech(String text) throws TtsException {
        // 初始化一个AipSpeech
        AipSpeech client = new AipSpeech(config.getAppId(), config.getApiKey(), config.getSecretKey());

        // 可选：设置网络连接参数
        client.setConnectionTimeoutInMillis(5000);
        client.setSocketTimeoutInMillis(60000);

        HashMap<String, Object> options = new HashMap<>(3);
        options.put(TtsConstants.BAIDU_TTS_OPTIONS.SPEAK_SPEED, SPEAK_SPEED_DEFAULT_VALUE);
        options.put(TtsConstants.BAIDU_TTS_OPTIONS.SPEAK_TONE, SPEAK_TONE_DEFAULT_VALUE);
        options.put(TtsConstants.BAIDU_TTS_OPTIONS.SPEAK_PER, SPEAK_PER_DEFAULT_VALUE_DUXIAOMEI);
        options.put(TtsConstants.BAIDU_TTS_OPTIONS.SPEAK_AUE, SPEAK_AUE_DEFAULT_VALUE);

        try {
            TtsResponse res = client.synthesis(text, SPEAK_LANGUAGE_DEFAULT_VALUE, 1, options);
            return KiwiAssertUtils.assertNotEmpty(res.getData(), "{} TTS generated bytes must not be null.",
                    TtsSourceEnum.BAIDU.getSource());
        } catch (Exception e) {
            log.error(e.getMessage(), e);
            throw new TtsException("%s TTS speech failed, text=%s", TtsSourceEnum.BAIDU.getSource(), text);
        }
    }

}
