# 加解密根密码
jasypt:
  encryptor:
    password: ${KIWI_ENC_PASSWORD} #根密码
    poolSize: 2

spring:
  redis:
    host: kiwi-redis
    password: ENC(uxuSI1Bl5AelC8dYvJUvMhsRbasVD4zh)
    port: 6379
  servlet:
    multipart:
      enabled: true
      max-file-size: 10MB
      max-request-size: 20MB
  rabbitmq:
    host: kiwi-rabbitmq
    port: 5672
    username: ENC(K6oRfaFZN7XSXbmJrXHiXQ==)
    password: ENC(cvON8OapdxM7/Tq88I5JuA==)
  elasticsearch:
    rest:
      uris: kiwi-es:9200
      username: ENC(NKy6wa5SuHBhQmfLWf6Zv8wf8sPMaE0b)
      password: ENC(oj9wNYu52oQH1d9T0zHeGDLz7P7em71u)
  main:
    allow-bean-definition-overriding: true
#  sleuth:
#    web:
#      client:
#        enabled: true
#    sampler:
#      # 默认的采样比率为0.1，不能看到所有请求数据
#      # 更改采样比率为1，就能看到所有的请求数据了，但是这样会增加接口调用延迟
#      probability: 1.0


# feign 配置
feign:
  hystrix:
    enabled: true
  okhttp:
    enabled: true
  httpclient:
    enabled: false
  client:
    config:
      default:
        connectTimeout: 60000
        readTimeout: 60000

# hystrix 配置
hystrix:
  threadpool:
    default:
      # 配置线程池
      coreSize: 100
      queueSizeRejectionThreshold: 120
  command:
    default:
      circuitBreaker:
        requestVolumeThreshold: 150
      execution:
        isolation:
          strategy: SEMAPHORE
          semaphore:
            maxConcurrentRequests: 120
          thread:
            timeoutInMilliseconds: 100000
  shareSecurityContext: true

#请求处理的超时时间
ribbon:
  ReadTimeout: 100000
  ConnectTimeout: 100000

# mybaits-plus配置
mybatis-plus:
  mapper-locations: classpath*:mapper/**/*Mapper.xml
  global-config:
    banner: false
    db-config:
      id-type: id_worker
      table-underline: true
      logic-delete-value: 1
      logic-not-delete-value: 0
      select-strategy: NOT_EMPTY
  configuration:
    map-underscore-to-camel-case: true
#    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl

# spring security 配置
security:
  oauth2:
    resource:
      loadBalanced: true
      token-info-uri: http://kiwi-auth/oauth/check_token

fdfs:
  connect-timeout: 6000000
  so-timeout: 6000000
  thumb-image:
    width: 150
    height: 150
  tracker-list: kiwi-fastdfs:22122

# 避免 Elasticsearch health check failed 异常
management:
  health:
    elasticsearch:
      enabled: false

tts:
  baidu:
    app-id: "20116041"
    api-key: "lTZsmSq37OtRKj6WDpjeemip"
    secret-key: "iQkIhGf6O93FH8Dhe446w8rB3jd2A137"
  voicerss:
    url: 'https://api.voicerss.org/?key={}&r=-2&hl=en-us&v=Mary&c=MP3&f=16khz_16bit_stereo&src=test'
    api-key-1: '02df0a8f48b641548ec4224c24ebff0e'
    api-key-2: '0e3c0a35570543249f743f74c027ef8b'
    api-key-3: 'a65b84ea89b14011af581b3335e40d63'
    api-key-4: '587527ea30b44778b6bbca2bcac95f38'
    api-key-5: '664f011d4efc4937b4d75a8b962f0323'
    api-key-6: '59a1e3301e4943edaab90166e3c1aafb'
    api-key-7: '58d4baef52414088998cbbda9751c8e2'
    api-key-8: '484727a997cb46458741fa3bd361d9cc'
    api-key-9: '38825b383ed54a10a8e43b8e6fc87157'
    api-key-10: 'b5c1a89b9f8a4ddf877dbe324ed6dc31'
    api-key-11: 'bb264a8707224eb3bd6016be38ac79f4'
    api-key-12: 'e99c0f6ed10a4413944d5e38c11af71f'
    api-key-13: '05df621e8aae400ba2129ef154446119'
    api-key-14: '43b6b8d3ea0148e6bc0bfe3023b15a76'
    api-key-15: 'c73302b470154c31b6da9b40e3ae37f1'
    api-key-16: '1d6ad4ecb6a941d28d24647e9c01e004'
    api-key-17: '37ab852142474b79877ccf1b69dc4710'
    api-key-18: '3744309a79ff48588fc1b63928c68c91'
    api-key-19: '3744309a79ff48588fc1b63928c68c91'
    api-key-20: 'd2f5e9a0fbf14318a475d808c0dddc62'

