spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(KH/GJ05cpFBSAV5u8IruRw==)
    password: ENC(Dh6vV+rX9HyZgiOP83BIiQAZ1+9KOGVh)
    url: jdbc:mysql://kiwi-db:3306/kiwi_db?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true&useSSL=false&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 60000
      connection-timeout: 60000
      maximum-pool-size: 100

me:
  fengorz:
    file:
      crawler:
        voice:
          tmpPath: "/wordTmp"
      vocabulary:
        word:
          list:
            path: "/wordTmp"



