mq:
  config:
    fetch:
      interval: 200
    wordFromCambridge:
      exchange: word
      fetchQueue: word.fetch
      fetchRouting: cambridge.fetch
      removeQueue: word.del
      removeRouting: cambridge.del
    phraseRunUpFromCambridge:
      exchange: phrase
      fetchQueue: phrase.fetch.runUp
      fetchRouting: cambridge.fetch.runUp
    phraseFromCambridge:
      exchange: phrase
      fetchQueue: phrase.fetch.real
      fetchRouting: cambridge.fetch.real
      removeQueue: phrase.del
      removeRouting: cambridge.del
    pronunciationFromCambridge:
      exchange: pronunciation
      fetchQueue: pronunciation.fetch
      fetchRouting: cambridge.fetch
      removeQueue: pronunciation.del
      removeRouting: cambridge.del

async:
  config:
    core:
      pool:
        size: 10
    max:
      pool:
        size: 20
    queue:
      capacity: 10

crawler:
  config:
    core:
      pool:
        size: 10
    max:
      pool:
        size: 20
    queue:
      capacity: 10

baidu:
  tts:
    app-id: 20116041
    api-key: lTZsmSq37OtRKj6WDpjeemip
    secret-key: iQkIhGf6O93FH8Dhe446w8rB3jd2A137

my:
  config:
    exclude-db: true