mq:
  config:
    fetch:
      interval: 200
    wordFetch:
      exchange: word.fetch
      queue:
        name: crawler
      routing:
        key: cambridge
    youdaoTranslate:
      exchange: youdao.translate
      queue:
        name: translateParaphrase
      routing:
        key: youdao


async:
  config:
    core:
      pool:
        size: 5
    max:
      pool:
        size: 15
    queue:
      capacity: 5

crawler:
  config:
    core:
      pool:
        #        size: 5
        size: 10
    max:
      pool:
        size: 15
    queue:
      capacity: 5

