mq:
  config:
    fetch:
      interval: 200
    word:
      fetch:
        exchange: word
        queue: crawler
        routing:
          cambridge: cambridge
      del:
        exchange: word
        queue: word.data.del
        routing:
          cambridge: cambridge
    pronunciation:
      fetch:
        exchange: pronunciation
        queue: pronunciation.fetch
        routing:
          cambridge: cambridge
      remove:
        exchange: pronunciation
        queue: pronunciation.remove
        routing:
          cambridge: cambridge
    youdao:
      exchange: youdao.translate
      queue:
        name: translateParaphrase
      routing:
        key: youdao


async:
  config:
    core:
      pool:
        size: 5
    max:
      pool:
        size: 15
    queue:
      capacity: 5

crawler:
  config:
    core:
      pool:
        #        size: 5
        size: 10
    max:
      pool:
        size: 15
    queue:
      capacity: 5

