me:
  fengorz:
    file:
      crawler:
        voice:
          tmpPath: "/Users/zhanshifeng/Documents/myDocument/temp/microSerivceVocabularyEnhancer"
      vocabulary:
        word:
          list:
            path: "/Users/zhanshifeng/Downloads"


