# 数据源
spring:
  main:
    allow-bean-definition-overriding: true

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /sys/user/**
    - /log/**

ms:
  config:
    exclude-db: false
    exclude-cache: false