mq:
  config:
    fetch:
      interval: 200
    word:
      fetch:
        exchange: word
        queue: crawler
        routing:
          cambridge: cambridgeCrawler
      remove:
        exchange: word
        queue: word.data.del
        routing:
          cambridge: cambridgeDel
    phrase:
      fetch:
        exchange: phrase
        queue:
          runUp: phrase.crawler.runUp
          real: phrase.crawler.real
        routing:
          cambridge:
            runUp: cambridge.runUp
            real: cambridge.real
      remove:
        exchange: phrase
        queue: phrase.data.del
        routing:
          cambridge: cambridgeDel
    pronunciation:
      fetch:
        exchange: pronunciation
        queue: pronunciation.fetch
        routing:
          cambridge: cambridgeFetch
      remove:
        exchange: pronunciation
        queue: pronunciation.remove
        routing:
          cambridge: cambridgeRemove
    youdao:
      exchange: youdao.translate
      queue:
        name: translateParaphrase
      routing:
        key: youdao


async:
  config:
    core:
      pool:
        size: 5
    max:
      pool:
        size: 15
    queue:
      capacity: 5

crawler:
  config:
    core:
      pool:
        size: 5
    max:
      pool:
        size: 10
    queue:
      capacity: 5

