# 数据源
spring:
  main:
    allow-bean-definition-overriding: true

flowable:
  async-executor-activate: false

# 开启Flowable Actuator Endpoints
management:
  endpoint:
    flowable:
      enabled: true

