mq:
  config:
    fetch:
      interval: 200
    wordFromCambridge:
      exchange: word
      fetchQueue: word.fetch
      fetchRouting: cambridge.fetch
      removeQueue: word.del
      removeRouting: cambridge.del
    phraseRunUpFromCambridge:
      exchange: phrase
      fetchQueue: phrase.fetch.runUp
      fetchRouting: cambridge.fetch.runUp
    phraseFromCambridge:
      exchange: phrase
      fetchQueue: phrase.fetch.real
      fetchRouting: cambridgefetch.real
      removeQueue: phrase.del
      removeRouting: cambridge.del
    pronunciationFromCambridge:
      exchange: pronunciation
      fetchQueue: pronunciation.fetch
      fetchRouting: cambridge.fetch
      removeQueue: phrase.del
      removeRouting: cambridge.del

async:
  config:
    core:
      pool:
        size: 5
    max:
      pool:
        size: 15
    queue:
      capacity: 5

crawler:
  config:
    core:
      pool:
        size: 5
    max:
      pool:
        size: 10
    queue:
      capacity: 5

