# 数据源
spring:
  main:
    allow-bean-definition-overriding: true

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /sys/user/info/*
    - /log/**
    - /sys/user/oneClickRegister

my:
  config:
    exclude-db: false
    exclude-redis: false