# 数据源
spring:
  datasource:
    type: com.zaxxer.hikari.HikariDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ENC(2PE/BMMoNPbRCEaIyGfcSw==)
    password: ENC(zF1rDpn+u8RZX5OTor7BpHzprZyrH+3P)
    url: jdbc:mysql://${db.ip}:3306/kiwi_db?useUnicode=true&characterEncoding=UTF-8&useSSL=false&autoReconnect=true&serverTimezone=Asia/Shanghai
    hikari:
      max-lifetime: 60000
      connection-timeout: 60000
      maximum-pool-size: 10
  main:
    allow-bean-definition-overriding: true

# 直接放行URL
ignore:
  urls:
    - /actuator/**
    - /sys/user/info/*
    - /log/**
    - /sys/user/oneClickRegister
