security:
  oauth2:
    client:
      client-id: ENC(wORgugqWfXlIuzbal/3pjXTNXij/RSpo)
      client-secret: ENC(rMd1buB3iI+si+W99eB+QFa3QburIEmY)
      scope: server

# 数据源
spring:
  main:
    allow-bean-definition-overriding: true

# 直接放行URL
ignore:
  urls:
    - /test/**
    - /word/main/query/**
    - /word/main/fuzzyQueryList/**
  userNames:
    - admin

me:
  fengorz:
    file:
      crawler:
        voice:
#          tmpPath: "/Users/zhanshifeng/Documents/myDocument/temp/microSerivceVocabularyEnhancer"
#          tmpPath: "~/crawlerTmp"
          tmpPath: "/root/crawlerTmp"

async:
  config:
    core:
      pool:
        size: 5
    max:
      pool:
        size: 15
    queue:
      capacity: 5


