spring:
  rabbitmq:
    host: kiwi-rabbitmq
    port: 5672
    username: guest
    password: guest
  main:
    allow-bean-definition-overriding: true

mq:
  config:
    fetch:
      interval: 200
    wordFetch:
      exchange: word.fetch
      queue:
        name: crawler
      routing:
        key: cambridge
    youdaoTranslate:
      exchange: youdao.translate
      queue:
        name: translateParaphrase
      routing:
        key: youdao


async:
  config:
    core:
      pool:
        size: 15
    max:
      pool:
        size: 30
    queue:
      capacity: 5

