services:
  kiwi-eureka:
    image: kiwi-eureka:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    ports:
      - '8762:8762'
    volumes:
      - ~/docker/kiwi/eureka/logs:/logs:Z
    network_mode: "host"
    healthcheck:
      test: ["CMD-SHELL", "code=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8762/actuator/health); [ \"$$code\" = \"200\" ] || [ \"$$code\" = \"401\" ] || [ \"$$code\" = \"403\" ]"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 3m

  kiwi-config:
    image: kiwi-config:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    ports:
      - '7771:7771'
    volumes:
      - ~/docker/kiwi/config/logs:/logs:Z
    network_mode: "host"
    depends_on:
      - kiwi-eureka
    healthcheck:
      test: ["CMD-SHELL", "code=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:7771/actuator/health); [ \"$$code\" = \"200\" ] || [ \"$$code\" = \"401\" ] || [ \"$$code\" = \"403\" ]"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 3m
    entrypoint:
      - /bin/sh
      - -c
      - |
        echo "Waiting for kiwi-eureka to be healthy..."
        wait_secs=0
        until code=$(curl -s -o /dev/null -w '%{http_code}' http://localhost:8762/actuator/health); [ "$$code" = "200" ] || [ "$$code" = "401" ] || [ "$$code" = "403" ]; do
          wait_secs=$$((wait_secs+1))
          if [ $$((wait_secs % 5)) -eq 0 ]; then
            echo "Waiting for kiwi-eureka to be healthy... ($$wait_secs s)"
          fi
          sleep 10
        done
        echo "kiwi-eureka is healthy. Starting kiwi-config..."
        exec java -Xmx128m \
          -Duser.timezone=GMT+12 \
          -jar /app.jar
