services:
  kiwi-eureka:
    image: kiwi-eureka:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    ports:
      - '8762:8762'
    volumes:
      - ~/docker/kiwi/eureka/logs:/logs:Z
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8762/health"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 3m

  kiwi-config:
    image: kiwi-config:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    ports:
      - '7771:7771'
    volumes:
      - ~/docker/kiwi/config/logs:/logs:Z
    network_mode: "host"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:7771/health"]
      interval: 30s
      timeout: 10s
      retries: 4
      start_period: 3m
    depends_on:
      - kiwi-eureka