services:
  kiwi-word-biz:
    image: kiwi-word-biz:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/word/logs:/logs:Z
      - /root/docker/kiwi/word/bizTmp:/wordTmp:Z
    network_mode: "host"
  kiwi-crawler:
    image: kiwi-crawler:2.0
    user: root
    restart: always
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/crawler/logs:/logs:Z
      - /root/docker/kiwi/crawler/tmp:/crawlerTmp:Z
    network_mode: "host"
    depends_on:
      - kiwi-word-biz


