services:
  kiwi-eureka:
    image: kiwi-eureka:2.0
    container_name: kiwi-eureka-2
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    ports:
      - '8762:8762'
    volumes:
      - /root/docker/kiwi/eureka/logs:/logs
    network_mode: "host"
  kiwi-config:
    image: kiwi-config:2.0
    container_name: kiwi-config-2
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    ports:
      - '7771:7771'
    volumes:
      - /root/docker/kiwi/config/logs:/logs
    network_mode: "host"
    depends_on:
      - kiwi-eureka
