services:
  kiwi-gate:
    image: kiwi-gate:2.0
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/gate/logs:/logs
    network_mode: "host"
  kiwi-upms:
    image: kiwi-upms:2.0
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/upms/logs:/logs
    network_mode: "host"
  kiwi-auth:
    image: kiwi-auth:2.0
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/auth/logs:/logs
    network_mode: "host"
  kiwi-word-biz:
    image: kiwi-word-biz:2.0
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/word/logs:/logs
      - /root/docker/kiwi/word/bizTmp:/wordTmp
    network_mode: "host"
    depends_on:
      - kiwi-gate
  kiwi-ai-biz:
    image: kiwi-ai-biz:2.0
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/ai/logs:/logs
      - /root/docker/kiwi/ai/tmp:/ai-tmp
    network_mode: "host"
    depends_on:
      - kiwi-gate
  kiwi-crawler:
    image: kiwi-crawler:2.0
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/crawler/logs:/logs
      - /root/docker/kiwi/crawler/tmp:/crawlerTmp
    network_mode: "host"
    depends_on:
      - kiwi-gate
      - kiwi-word-biz

