services:
  kiwi-gate:
    image: kiwi-gate:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/gate/logs:/logs:Z
    network_mode: "host"
  kiwi-upms:
    image: kiwi-upms:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/upms/logs:/logs:Z
    network_mode: "host"
  kiwi-auth:
    image: kiwi-auth:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
    volumes:
      - /root/docker/kiwi/auth/logs:/logs:Z
    network_mode: "host"
  kiwi-word-biz:
    image: kiwi-word-biz:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
      - GCP_API_KEY=${GCP_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - /root/docker/kiwi/word/logs:/logs:Z
      - /root/docker/kiwi/word/bizTmp:/wordTmp:Z
    network_mode: "host"
    depends_on:
      - kiwi-gate
  kiwi-ai-biz:
    image: kiwi-ai-biz:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
      - GROK_API_KEY=${GROK_API_KEY}
      - YTB_OAUTH_CLIENT_SECRETS_FILE=${YTB_OAUTH_CLIENT_SECRETS_FILE}
      - YTB_OAUTH_ACCESS_TOKEN=${YTB_OAUTH_ACCESS_TOKEN}
    volumes:
      - /root/docker/kiwi/ai/logs:/logs:Z
      - /root/docker/kiwi/ai/tmp:/ai-tmp:Z
    network_mode: "host"
    depends_on:
      - kiwi-gate
  kiwi-crawler:
    image: kiwi-crawler:2.0
    user: root
    environment:
      - KIWI_ENC_PASSWORD=${KIWI_ENC_PASSWORD}
      - DB_IP=${DB_IP}
      - GCP_API_KEY=${GCP_API_KEY}
      - GOOGLE_APPLICATION_CREDENTIALS=${GOOGLE_APPLICATION_CREDENTIALS}
    volumes:
      - /root/docker/kiwi/crawler/logs:/logs:Z
      - /root/docker/kiwi/crawler/tmp:/crawlerTmp:Z
    network_mode: "host"
    depends_on:
      - kiwi-gate
      - kiwi-word-biz

