#!/bin/bash
# Infrastructure management script for Kiwi Monolith
# Usage: ./infra.sh [setup|start|stop|restart|status|logs|clean|backup-db|restore-db|backup-ftp|restore-ftp]

set -e

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
cd "$SCRIPT_DIR"

# Colors for output
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
BLUE='\033[0;34m'
CYAN='\033[0;36m'
BOLD='\033[1m'
NC='\033[0m' # No Color

# Configuration
MAX_WAIT_SECONDS=120
HEALTH_CHECK_INTERVAL=3

log_info() {
    echo -e "${GREEN}[INFO]${NC} $1"
}

log_warn() {
    echo -e "${YELLOW}[WARN]${NC} $1"
}

log_error() {
    echo -e "${RED}[ERROR]${NC} $1"
}

log_step() {
    echo -e "${BLUE}[STEP]${NC} ${BOLD}$1${NC}"
}

log_success() {
    echo -e "${GREEN}[✓]${NC} $1"
}

# ==================== Prerequisites Check ====================

check_command() {
    if ! command -v "$1" &> /dev/null; then
        return 1
    fi
    return 0
}

check_prerequisites() {
    local missing=()

    log_step "Checking prerequisites..."

    # Check Docker
    if ! check_command docker; then
        missing+=("docker")
    elif ! docker info &>/dev/null; then
        log_error "Docker is installed but not running. Please start Docker Desktop."
        exit 1
    else
        log_success "Docker is available"
    fi

    # Check docker-compose (try both versions)
    if check_command docker-compose; then
        COMPOSE_CMD="docker-compose"
        log_success "docker-compose is available"
    elif docker compose version &>/dev/null 2>&1; then
        COMPOSE_CMD="docker compose"
        log_success "docker compose is available"
    else
        missing+=("docker-compose")
    fi

    if [ ${#missing[@]} -ne 0 ]; then
        log_error "Missing required tools: ${missing[*]}"
        echo ""
        echo "Please install the missing tools:"
        for tool in "${missing[@]}"; do
            case $tool in
                docker)
                    echo "  - Docker: https://docs.docker.com/get-docker/"
                    ;;
                docker-compose)
                    echo "  - Docker Compose: https://docs.docker.com/compose/install/"
                    ;;
            esac
        done
        exit 1
    fi

    log_success "All prerequisites satisfied"
}

# ==================== Environment Setup ====================

setup_env() {
    if [ -f ".env" ]; then
        log_info "Environment file .env already exists"
        return 0
    fi

    log_step "Setting up environment configuration..."

    # Determine which template to use
    local env_template=".env.dev"
    if [ -n "$1" ] && [ -f ".env.$1" ]; then
        env_template=".env.$1"
    fi

    if [ -f "$env_template" ]; then
        cp "$env_template" .env
        log_success "Created .env from $env_template"
    else
        # Create minimal .env file
        cat > .env << 'EOF'
# Kiwi Infrastructure Configuration
# Generated by infra.sh setup

# Database
DB_HOST=localhost
DB_PORT=3307
DB_NAME=kiwi_db
DB_USERNAME=root
DB_PASSWORD=kiwi123

# Redis
REDIS_HOST=localhost
REDIS_PORT=6380
REDIS_PASSWORD=kiwi123

# Elasticsearch
ES_PORT=9201
ES_PASSWORD=changeme

# Timezone
TZ=Pacific/Auckland
EOF
        log_success "Created default .env configuration"
    fi

    log_info "You can customize settings in .env file"
}

load_env() {
    if [ -f ".env" ]; then
        set -a
        source .env
        set +a
    fi
}

# Backup directory (after env is loaded)
init_backup_dir() {
    BACKUP_DIR="${BACKUP_DIR:-$SCRIPT_DIR/backups}"
    mkdir -p "$BACKUP_DIR"
}

start_infra() {
    log_step "Starting infrastructure services..."
    $COMPOSE_CMD up -d

    log_step "Waiting for services to be healthy..."

    # Wait for MySQL with timeout
    wait_for_mysql

    # Wait for Redis with timeout
    wait_for_redis

    # Wait for Elasticsearch with timeout
    wait_for_elasticsearch

    # Create Elasticsearch index if not exists
    create_es_index

    echo ""
    log_success "All infrastructure services are running!"
    show_status
}

wait_for_mysql() {
    local elapsed=0
    echo -n "  MySQL: "

    while [ $elapsed -lt $MAX_WAIT_SECONDS ]; do
        if docker exec kiwi-mysql mysqladmin ping -h localhost -u root -p"${DB_PASSWORD:-kiwi123}" --silent 2>/dev/null; then
            echo -e " ${GREEN}ready${NC}"
            return 0
        fi
        echo -n "."
        sleep $HEALTH_CHECK_INTERVAL
        elapsed=$((elapsed + HEALTH_CHECK_INTERVAL))
    done

    echo -e " ${RED}timeout${NC}"
    log_error "MySQL failed to start within ${MAX_WAIT_SECONDS}s"
    exit 1
}

wait_for_redis() {
    local elapsed=0
    echo -n "  Redis: "

    while [ $elapsed -lt $MAX_WAIT_SECONDS ]; do
        if docker exec kiwi-redis redis-cli -a "${REDIS_PASSWORD:-kiwi123}" ping 2>/dev/null | grep -q PONG; then
            echo -e " ${GREEN}ready${NC}"
            return 0
        fi
        echo -n "."
        sleep $HEALTH_CHECK_INTERVAL
        elapsed=$((elapsed + HEALTH_CHECK_INTERVAL))
    done

    echo -e " ${RED}timeout${NC}"
    log_error "Redis failed to start within ${MAX_WAIT_SECONDS}s"
    exit 1
}

wait_for_elasticsearch() {
    local elapsed=0
    echo -n "  Elasticsearch: "

    while [ $elapsed -lt $MAX_WAIT_SECONDS ]; do
        if curl -s -u "elastic:${ES_PASSWORD:-changeme}" "http://localhost:${ES_PORT:-9201}/_cluster/health" 2>/dev/null | grep -q '"status"'; then
            echo -e " ${GREEN}ready${NC}"
            return 0
        fi
        echo -n "."
        sleep $HEALTH_CHECK_INTERVAL
        elapsed=$((elapsed + HEALTH_CHECK_INTERVAL))
    done

    echo -e " ${RED}timeout${NC}"
    log_error "Elasticsearch failed to start within ${MAX_WAIT_SECONDS}s"
    exit 1
}

stop_infra() {
    log_step "Stopping infrastructure services..."
    $COMPOSE_CMD down
    log_success "Infrastructure stopped."
}

restart_infra() {
    stop_infra
    echo ""
    start_infra
}

show_status() {
    echo ""
    echo -e "${BOLD}Infrastructure Status:${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    $COMPOSE_CMD ps
    echo ""
    echo -e "${BOLD}Connection Info:${NC}"
    echo "━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━"
    echo -e "  ${CYAN}MySQL${NC}         : localhost:${DB_PORT:-3307}"
    echo "                  user: root, password: ${DB_PASSWORD:-kiwi123}"
    echo -e "  ${CYAN}Redis${NC}         : localhost:${REDIS_PORT:-6380}"
    echo "                  password: ${REDIS_PASSWORD:-kiwi123}"
    echo -e "  ${CYAN}Elasticsearch${NC} : http://localhost:${ES_PORT:-9201}"
    echo "                  user: elastic, password: ${ES_PASSWORD:-changeme}"
    echo ""
}

show_logs() {
    SERVICE=${2:-}
    if [ -z "$SERVICE" ]; then
        $COMPOSE_CMD logs -f
    else
        $COMPOSE_CMD logs -f "$SERVICE"
    fi
}

clean_infra() {
    log_warn "This will remove all data volumes! Are you sure? (y/N)"
    read -r response
    if [[ "$response" =~ ^[Yy]$ ]]; then
        log_step "Stopping and removing containers and volumes..."
        $COMPOSE_CMD down -v
        log_success "Cleanup complete."
    else
        log_info "Cleanup cancelled."
    fi
}

create_es_index() {
    ES_URL="http://localhost:${ES_PORT:-9201}"
    ES_AUTH="elastic:${ES_PASSWORD:-changeme}"
    INDEX_NAME="kiwi_vocabulary"

    # Check if index exists
    if curl -s -u "$ES_AUTH" "$ES_URL/$INDEX_NAME" 2>/dev/null | grep -q "\"$INDEX_NAME\""; then
        log_info "Elasticsearch index '$INDEX_NAME' already exists."
    else
        log_info "Creating Elasticsearch index '$INDEX_NAME'..."
        curl -s -X PUT -u "$ES_AUTH" "$ES_URL/$INDEX_NAME" \
            -H "Content-Type: application/json" \
            -d '{
                "settings": {
                    "number_of_shards": 1,
                    "number_of_replicas": 0,
                    "analysis": {
                        "analyzer": {
                            "kiwi_analyzer": {
                                "type": "custom",
                                "tokenizer": "standard",
                                "filter": ["lowercase", "asciifolding"]
                            }
                        }
                    }
                },
                "mappings": {
                    "properties": {
                        "wordName": { "type": "text", "analyzer": "kiwi_analyzer" },
                        "wordId": { "type": "long" },
                        "infoType": { "type": "integer" },
                        "paraphraseText": { "type": "text", "analyzer": "kiwi_analyzer" }
                    }
                }
            }' > /dev/null
        log_info "Elasticsearch index created."
    fi
}

# ==================== Database Backup/Restore ====================

backup_db() {
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="$BACKUP_DIR/kiwi_db_${TIMESTAMP}.sql.gz"

    log_info "Starting MySQL database backup..."

    # Check if MySQL container is running
    if ! docker ps --format '{{.Names}}' | grep -q '^kiwi-mysql$'; then
        log_error "MySQL container is not running. Please start infrastructure first."
        exit 1
    fi

    # Create backup using mysqldump
    docker exec kiwi-mysql mysqldump \
        -u root \
        -p"${DB_PASSWORD:-kiwi123}" \
        --single-transaction \
        --routines \
        --triggers \
        --databases "${DB_NAME:-kiwi_db}" \
        2>/dev/null | gzip > "$BACKUP_FILE"

    if [ -s "$BACKUP_FILE" ]; then
        BACKUP_SIZE=$(du -h "$BACKUP_FILE" | cut -f1)
        log_info "Database backup completed successfully!"
        log_info "Backup file: $BACKUP_FILE ($BACKUP_SIZE)"
    else
        rm -f "$BACKUP_FILE"
        log_error "Backup failed - empty backup file"
        exit 1
    fi

    # List recent backups
    echo ""
    log_info "Recent database backups:"
    ls -lh "$BACKUP_DIR"/kiwi_db_*.sql.gz 2>/dev/null | tail -5 || echo "  No backups found"
}

restore_db() {
    BACKUP_FILE="${2:-}"

    if [ -z "$BACKUP_FILE" ]; then
        # List available backups
        echo ""
        log_info "Available database backups:"
        echo "----------------------------------------"
        ls -lht "$BACKUP_DIR"/kiwi_db_*.sql.gz 2>/dev/null || { log_error "No backups found in $BACKUP_DIR"; exit 1; }
        echo "----------------------------------------"
        echo ""
        log_warn "Usage: $0 restore-db <backup_file>"
        log_info "Example: $0 restore-db $BACKUP_DIR/kiwi_db_20240101_120000.sql.gz"
        exit 1
    fi

    # Check if backup file exists
    if [ ! -f "$BACKUP_FILE" ]; then
        log_error "Backup file not found: $BACKUP_FILE"
        exit 1
    fi

    # Check if MySQL container is running
    if ! docker ps --format '{{.Names}}' | grep -q '^kiwi-mysql$'; then
        log_error "MySQL container is not running. Please start infrastructure first."
        exit 1
    fi

    log_warn "This will OVERWRITE the current database! Are you sure? (y/N)"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        log_info "Restore cancelled."
        exit 0
    fi

    log_info "Restoring database from: $BACKUP_FILE"

    # Restore from backup
    gunzip -c "$BACKUP_FILE" | docker exec -i kiwi-mysql mysql \
        -u root \
        -p"${DB_PASSWORD:-kiwi123}" \
        2>/dev/null

    if [ $? -eq 0 ]; then
        log_info "Database restore completed successfully!"
    else
        log_error "Database restore failed!"
        exit 1
    fi
}

# ==================== FTP Backup/Restore ====================

backup_ftp() {
    TIMESTAMP=$(date +%Y%m%d_%H%M%S)
    BACKUP_FILE="$BACKUP_DIR/kiwi_ftp_${TIMESTAMP}.tar.gz"
    FTP_HOST="${FTP_HOST:-localhost}"
    FTP_PORT="${FTP_PORT:-21}"
    FTP_USER="${FTP_USER:-ftpuser}"
    FTP_PASS="${FTP_PASS:-ftppass}"
    FTP_REMOTE_DIR="${FTP_REMOTE_DIR:-/}"
    FTP_LOCAL_TEMP="$BACKUP_DIR/.ftp_temp_$$"

    log_info "Starting FTP backup..."
    log_info "FTP Host: $FTP_HOST:$FTP_PORT"
    log_info "Remote directory: $FTP_REMOTE_DIR"

    # Create temp directory
    mkdir -p "$FTP_LOCAL_TEMP"

    # Download all files from FTP using lftp (preferred) or curl
    log_info "Downloading files from FTP server..."

    if command -v lftp &> /dev/null; then
        lftp -u "$FTP_USER","$FTP_PASS" "ftp://$FTP_HOST:$FTP_PORT" -e "mirror $FTP_REMOTE_DIR $FTP_LOCAL_TEMP; quit" 2>/dev/null
        RESULT=$?
    else
        # Fallback to curl
        log_warn "lftp not found, using curl"
        cd "$FTP_LOCAL_TEMP"
        curl -s -u "$FTP_USER:$FTP_PASS" "ftp://$FTP_HOST:$FTP_PORT$FTP_REMOTE_DIR" -o listing.txt 2>/dev/null
        # Parse listing and download files (basic implementation)
        while IFS= read -r line; do
            filename=$(echo "$line" | awk '{print $NF}')
            if [ -n "$filename" ] && [ "$filename" != "." ] && [ "$filename" != ".." ]; then
                curl -s -u "$FTP_USER:$FTP_PASS" "ftp://$FTP_HOST:$FTP_PORT$FTP_REMOTE_DIR/$filename" -o "$filename" 2>/dev/null
            fi
        done < listing.txt
        rm -f listing.txt
        cd "$SCRIPT_DIR"
        RESULT=0
    fi

    # Create tar archive
    if [ -d "$FTP_LOCAL_TEMP" ] && [ "$(ls -A "$FTP_LOCAL_TEMP" 2>/dev/null)" ]; then
        tar -czf "$BACKUP_FILE" -C "$FTP_LOCAL_TEMP" .
        BACKUP_SIZE=$(du -h "$BACKUP_FILE" | cut -f1)
        log_info "FTP backup completed successfully!"
        log_info "Backup file: $BACKUP_FILE ($BACKUP_SIZE)"
    else
        log_error "No files downloaded from FTP server"
        rm -rf "$FTP_LOCAL_TEMP"
        exit 1
    fi

    # Cleanup temp directory
    rm -rf "$FTP_LOCAL_TEMP"

    # List recent backups
    echo ""
    log_info "Recent FTP backups:"
    ls -lh "$BACKUP_DIR"/kiwi_ftp_*.tar.gz 2>/dev/null | tail -5 || echo "  No backups found"
}

restore_ftp() {
    BACKUP_FILE="${2:-}"
    FTP_HOST="${FTP_HOST:-localhost}"
    FTP_PORT="${FTP_PORT:-21}"
    FTP_USER="${FTP_USER:-ftpuser}"
    FTP_PASS="${FTP_PASS:-ftppass}"
    FTP_REMOTE_DIR="${FTP_REMOTE_DIR:-/}"
    FTP_LOCAL_TEMP="$BACKUP_DIR/.ftp_temp_$$"

    if [ -z "$BACKUP_FILE" ]; then
        # List available backups
        echo ""
        log_info "Available FTP backups:"
        echo "----------------------------------------"
        ls -lht "$BACKUP_DIR"/kiwi_ftp_*.tar.gz 2>/dev/null || { log_error "No backups found in $BACKUP_DIR"; exit 1; }
        echo "----------------------------------------"
        echo ""
        log_warn "Usage: $0 restore-ftp <backup_file>"
        log_info "Example: $0 restore-ftp $BACKUP_DIR/kiwi_ftp_20240101_120000.tar.gz"
        exit 1
    fi

    # Check if backup file exists
    if [ ! -f "$BACKUP_FILE" ]; then
        log_error "Backup file not found: $BACKUP_FILE"
        exit 1
    fi

    log_warn "This will upload files to FTP server at $FTP_HOST:$FTP_PORT$FTP_REMOTE_DIR"
    log_warn "Existing files may be OVERWRITTEN! Are you sure? (y/N)"
    read -r response
    if [[ ! "$response" =~ ^[Yy]$ ]]; then
        log_info "Restore cancelled."
        exit 0
    fi

    log_info "Restoring FTP from: $BACKUP_FILE"
    log_info "Target FTP: $FTP_HOST:$FTP_PORT$FTP_REMOTE_DIR"

    # Extract to temp directory
    mkdir -p "$FTP_LOCAL_TEMP"
    tar -xzf "$BACKUP_FILE" -C "$FTP_LOCAL_TEMP"

    # Upload files to FTP
    if command -v lftp &> /dev/null; then
        lftp -u "$FTP_USER","$FTP_PASS" "ftp://$FTP_HOST:$FTP_PORT" -e "mirror -R $FTP_LOCAL_TEMP $FTP_REMOTE_DIR; quit" 2>/dev/null
        RESULT=$?
    else
        # Fallback: upload files one by one with curl
        log_warn "lftp not found, using curl for upload"
        RESULT=0
        find "$FTP_LOCAL_TEMP" -type f | while read file; do
            RELATIVE_PATH="${file#$FTP_LOCAL_TEMP/}"
            curl -s -T "$file" -u "$FTP_USER:$FTP_PASS" "ftp://$FTP_HOST:$FTP_PORT$FTP_REMOTE_DIR/$RELATIVE_PATH" --ftp-create-dirs 2>/dev/null || RESULT=1
        done
    fi

    # Cleanup
    rm -rf "$FTP_LOCAL_TEMP"

    if [ $RESULT -eq 0 ]; then
        log_info "FTP restore completed successfully!"
    else
        log_error "FTP restore failed!"
        exit 1
    fi
}

list_backups() {
    echo ""
    log_info "=== Database Backups ==="
    ls -lht "$BACKUP_DIR"/kiwi_db_*.sql.gz 2>/dev/null || echo "  No database backups found"
    echo ""
    log_info "=== FTP Backups ==="
    ls -lht "$BACKUP_DIR"/kiwi_ftp_*.tar.gz 2>/dev/null || echo "  No FTP backups found"
    echo ""
    log_info "Backup directory: $BACKUP_DIR"
}

# ==================== One-Command Setup ====================

setup_infrastructure() {
    echo ""
    echo -e "${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║       Kiwi Monolith Infrastructure Setup                  ║${NC}"
    echo -e "${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""

    local env_profile="${2:-dev}"

    # Step 1: Check prerequisites
    check_prerequisites

    # Step 2: Setup environment
    echo ""
    setup_env "$env_profile"

    # Step 3: Load environment
    load_env
    init_backup_dir

    # Step 4: Pull images
    echo ""
    log_step "Pulling Docker images (this may take a while on first run)..."
    $COMPOSE_CMD pull

    # Step 5: Start services
    echo ""
    start_infra

    # Final message
    echo ""
    echo -e "${BOLD}╔═══════════════════════════════════════════════════════════╗${NC}"
    echo -e "${BOLD}║       Setup Complete! Infrastructure is ready.            ║${NC}"
    echo -e "${BOLD}╚═══════════════════════════════════════════════════════════╝${NC}"
    echo ""
    echo "Next steps:"
    echo "  1. Start your Spring Boot application"
    echo "  2. Access MySQL: mysql -h localhost -P ${DB_PORT:-3307} -u root -p"
    echo "  3. View logs: $0 logs"
    echo ""
}

show_help() {
    echo -e "${BOLD}Kiwi Monolith Infrastructure Manager${NC}"
    echo ""
    echo -e "${BOLD}Usage:${NC} $0 <command> [options]"
    echo ""
    echo -e "${BOLD}Quick Start:${NC}"
    echo -e "  ${CYAN}setup${NC}      - ${GREEN}One-command setup${NC}: checks prerequisites, configures env,"
    echo "               pulls images, and starts all services"
    echo "               Options: setup [dev|test|prod] (default: dev)"
    echo ""
    echo -e "${BOLD}Service Management:${NC}"
    echo -e "  ${CYAN}start${NC}      - Start all infrastructure services"
    echo -e "  ${CYAN}stop${NC}       - Stop all infrastructure services"
    echo -e "  ${CYAN}restart${NC}    - Restart all infrastructure services"
    echo -e "  ${CYAN}status${NC}     - Show status of all services"
    echo -e "  ${CYAN}logs${NC}       - Show logs (optionally: logs <service>)"
    echo -e "  ${CYAN}clean${NC}      - Stop and remove all data ${RED}(WARNING: destroys data)${NC}"
    echo ""
    echo -e "${BOLD}Backup/Restore:${NC}"
    echo -e "  ${CYAN}backup-db${NC}  - Create a MySQL database backup"
    echo -e "  ${CYAN}restore-db${NC} - Restore MySQL from backup (restore-db <file>)"
    echo -e "  ${CYAN}backup-ftp${NC} - Download and backup files from FTP server"
    echo -e "  ${CYAN}restore-ftp${NC}- Upload backup files to FTP server (restore-ftp <file>)"
    echo -e "  ${CYAN}backups${NC}    - List all available backups"
    echo ""
    echo -e "${BOLD}Examples:${NC}"
    echo "  $0 setup              # First-time setup with default dev config"
    echo "  $0 setup prod         # Setup with production configuration"
    echo "  $0 start              # Start services (after initial setup)"
    echo "  $0 logs kiwi-mysql    # View MySQL logs"
    echo "  $0 backup-db          # Create database backup"
    echo ""
    echo -e "${BOLD}Environment Variables:${NC}"
    echo "  BACKUP_DIR     - Backup directory (default: ./backups)"
    echo "  FTP_HOST       - FTP server hostname (default: localhost)"
    echo "  FTP_PORT       - FTP server port (default: 21)"
    echo "  FTP_USER       - FTP username (default: ftpuser)"
    echo "  FTP_PASS       - FTP password (default: ftppass)"
    echo "  FTP_REMOTE_DIR - Remote directory to backup (default: /)"
    echo ""
}

# ==================== Main Entry Point ====================

main() {
    local cmd="${1:-}"

    # Commands that don't need prerequisites check
    case "$cmd" in
        help|-h|--help)
            show_help
            exit 0
            ;;
        "")
            show_help
            exit 1
            ;;
    esac

    # Check prerequisites for all other commands
    check_prerequisites

    # Load environment
    load_env
    init_backup_dir

    # Execute command
    case "$cmd" in
        setup)
            setup_infrastructure "$@"
            ;;
        start)
            start_infra
            ;;
        stop)
            stop_infra
            ;;
        restart)
            restart_infra
            ;;
        status)
            show_status
            ;;
        logs)
            show_logs "$@"
            ;;
        clean)
            clean_infra
            ;;
        backup-db)
            backup_db
            ;;
        restore-db)
            restore_db "$@"
            ;;
        backup-ftp)
            backup_ftp
            ;;
        restore-ftp)
            restore_ftp "$@"
            ;;
        backups)
            list_backups
            ;;
        *)
            log_error "Unknown command: $cmd"
            echo ""
            show_help
            exit 1
            ;;
    esac
}

# Run main function
main "$@"
