apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: storage0-deploy
    namespace: fastdfs
    labels:
        name: storage0-deploy
spec:
    replicas: 1
    template:
        metadata:
            labels:
                app: storage0
        spec:
            nodeSelector:
              fastdfs: storage0
            terminationGracePeriodSeconds: 0
            containers:
            - name: storage0
              image:  luhuiguo / fastdfs # indicates the address of the reference mirror
              imagePullPolicy: Always
              ports:
              - containerPort: 22122
              protocol:  TCP #port protocol, support TCP and UDP, default TCP
              volumeMounts:
              - name: storage0-volume
                mountPath: /var/fdfs
              env:
              - name: TRACKER_SERVER
                value: 10.96.0.110:22122
              command: ["/usr/bin/start.sh","storage"]
            volumes:
            - name: storage0-volume
              hostPath:
                path:  / home / data / fastdfs / storage0 # The address stored on the host machine can be configured by itself
