apiVersion: extensions/v1beta1
kind: Deployment
metadata:
    name: tracker-deploy # deployed container name
    namespace:  fastdfs # Namespace deployed to
    labels:
        name: tracker-deploy
spec: # Specification of the deployment
    replicas:  1 # Number of copies
    template:
        metadata:
            labels:
                app: tracker
        spec:
            nodeSelector:
              fastdfs:  tracker # selector, nodeSelector specifies which machine the pod starts from according to the label, modify it according to its own needs, you must first define this label on the node
            terminationGracePeriodSeconds: 0
            containers:
            - name: tracker
              image: luhuiguo/fastdfs
              imagePullPolicy:  Always #Strategy for obtaining images Always means downloading images IfNotPresent means giving priority to local images, otherwise downloading images, Nerver means using only local images
              ports:
              - containerPort: 22122
              protocol:  TCP #port protocol, support TCP and UDP, default TCP
              volumeMounts:
              - name: tracker-volume
                mountPath: /var/fdfs
              command: ["/usr/bin/start.sh","tracker"]
            volumes:
            - name: tracker-volume
              hostPath:
                path:  / home / data / fastdfs / tracker # address stored on the host machine
