apiVersion: v1
kind: Service
metadata:
    name: tracker
    labels:
        app: tracker
    namespace: fastdfs
spec:
    selector:
        app:  tracker # Here the selector must choose the label of the container
    type:  NodePort # This can be ClusterIP, but ClusterIP can only be called within the cluster, and cannot be accessed from the external network
    clusterIP: 10.96.0.110
    ports:
    - name: "22122"
      port: 22122
      targetPort: 22122
      nodePort: 22122

---
apiVersion: v1
kind: Service
metadata:
    name: storage0
    labels:
        app: storage0
    namespace: fastdfs
spec:
    selector:
        app: storage0
    type: NodePort
    ports:
    - name: "23000"
      port: 23000
      targetPort: 23000
      nodePort: 23000
