apiVersion: v1
kind: Namespace
metadata:
    name: kiwi-be-infrastructure

---

apiVersion: v1
kind: Namespace
metadata:
    name: kiwi-be-business

---

apiVersion: v1
kind: Namespace
metadata:
    name: kiwi-fe
