apiVersion: apps/v1
kind: Deployment
metadata:
  name: rabbitmq
  labels:
    app: rabbitmq
spec:
  replicas: 1
  selector:
    matchLabels:
      app: rabbitmq
  template:
    metadata:
      labels:
        app: rabbitmq
    spec:
      hostname: my-rabbit
      containers:
      - name: rabbitmq
        image: rabbitmq:3.8-management
        ports:
        - name: rabbitmq-web
          containerPort: 15672
        - name: rabbitmq-app
          containerPort: 5672
        volumeMounts:
        - name: persisitent-storage-rabbitmq
          mountPath: /var/lib/rabbitmq
        env:
        - name: RABBITMQ_DEFAULT_VHOST
          value: my_vhost
        - name: RABBITMQ_DEFAULT_USER
          value: admin
        - name: RABBITMQ_DEFAULT_PASS
          value: yourpassword
      volumes:
      - name: persisitent-storage-rabbitmq
        persistentVolumeClaim:
          claimName: efs-rabbitmq-pvc