package me.fengorz.kiwi.common.ytb;

import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

public class SubtitleExtractor {

    private static final Logger log = LoggerFactory.getLogger(SubtitleExtractor.class);

    public SubtitleAnalysisResult analyze(File subtitleFile) throws IOException {
        List<String> subtitles = new ArrayList<>();
        boolean isAutoGenerated = false;
        String lastText = null;
        String pendingTimestamp = null;

        try (BufferedReader reader = Files.newBufferedReader(subtitleFile.toPath(), StandardCharsets.UTF_8)) {
            String line;
            while ((line = reader.readLine()) != null) {
                // Skip empty lines
                if (line.trim().isEmpty()) {
                    continue;
                }

                // Check if this is a timestamp line
                if (line.matches("\\d{2}:\\d{2}:\\d{2}\\.\\d{3}\\s+-->\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d{3}.*")) {
                    // Remove position formatting
                    pendingTimestamp = cleanSubtitleLine(line);
                    continue;
                }

                // Check for auto-generated tags
                if (line.contains("<c>") && line.contains("</c>")) {
                    isAutoGenerated = true;
                    continue;
                }

                // Clean the subtitle line
                String cleanedLine = cleanSubtitleLine(line);

                // Skip if empty after cleaning
                if (cleanedLine.isEmpty()) {
                    continue;
                }

                // Skip if this is a duplicate of the previous text line
                if (StringUtils.equals(lastText, cleanedLine)) {
                    continue;
                }

                // If we have a pending timestamp, add it now
                if (pendingTimestamp != null) {
                    subtitles.add(pendingTimestamp);
                    pendingTimestamp = null;
                }

                subtitles.add(cleanedLine);
                lastText = cleanedLine;
            }
        }

        log.info("Subtitles content retrieved and cleaned. Is auto-generated: {}", isAutoGenerated);
        return new SubtitleAnalysisResult(subtitles, isAutoGenerated);
    }

    /**
     * Cleans subtitle line by removing HTML entities and formatting tags.
     *
     * @param line The raw subtitle line to clean
     * @return The cleaned subtitle text
     */
    private String cleanSubtitleLine(String line) {
        String result = line;
        result = result.replaceAll("&nbsp;", "")
                .replaceAll("\\s+align:start position:0%$", "");

        // Clean up multiple spaces and trim the result
        result = result.replaceAll("\\s+", " ").trim();

        return result;
    }

    public static class SubtitleAnalysisResult {
        private final List<String> subtitles;
        private final boolean isAutoGenerated;

        public SubtitleAnalysisResult(List<String> subtitles, boolean isAutoGenerated) {
            this.subtitles = subtitles;
            this.isAutoGenerated = isAutoGenerated;
        }

        public List<String> getSubtitles() {
            return subtitles;
        }

        public boolean isAutoGenerated() {
            return isAutoGenerated;
        }
    }
}
