apiVersion: apps/v1
kind: Deployment
metadata:
  name: kiwi-eureka
  namespace: kiwi-be-business
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kiwi-eureka
    matchExpressions:
    - {key: app, operator: In, values: [kiwi-eureka] }
  template:
    metadata:
      labels:
        app: kiwi-eureka
    spec:
      containers:
      - name: kiwi-eureka
        image: kiwi-eureka:1.0
        ports:
        - containerPort: 8762
        resources: {}
        volumeMounts:
        - mountPath: /logs
          name: kiwi-eureka-claim
      volumes:
      - name: kiwi-eureka-claim
        hostPath:
          path: /root/docker/kiwi/eureka/logs
status: {}