apiVersion: v1
kind: Service
metadata:
  labels:
    app: kiwi-eureka
  name: kiwi-eureka
  namespace: kiwi-be-business
spec:
  type: NodePort
  ports:
  - name: "8762"
    port: 8762
    targetPort: 8762
    nodePort: 31001
  selector:
    app: kiwi-eureka
status:
  loadBalancer: {}