apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: kiwi-config
  namespace: kiwi-be-business
spec:
  replicas: 1
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
  selector:
    matchLabels:
      app: kiwi-config
    matchExpressions:
    - {key: app, operator: In, values: [kiwi-eureka] }
  template:
    metadata:
      labels:
        app: kiwi-config
    spec:
      containers:
      - image: kiwi-config:1.0
        name: kiwi-config
        ports:
        - containerPort: 7771
        resources: {}
        volumeMounts:
        - mountPath: /logs
          name: kiwi-config-claim
      volumes:
      - name: kiwi-config-claim
        hostPath:
          path: /root/docker/kiwi/config/logs
status: {}
