/*
 * Copyright [2019~2025] [codingByFeng]
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package me.fengorz.kiwi.domain.ai.ytb;

import lombok.AllArgsConstructor;
import lombok.Getter;
import org.apache.commons.lang3.StringUtils;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.io.BufferedReader;
import java.io.File;
import java.io.IOException;
import java.nio.charset.StandardCharsets;
import java.nio.file.Files;
import java.util.ArrayList;
import java.util.List;

/**
 * Subtitle Extractor - extracts and analyzes subtitles from VTT files
 *
 * @author codingByFeng
 */
public class SubtitleExtractor {

    private static final Logger log = LoggerFactory.getLogger(SubtitleExtractor.class);

    public SubtitleAnalysisResult analyze(File subtitleFile) throws IOException {
        List<String> subtitles = new ArrayList<>();
        boolean isAutoGenerated = false;
        String lastText = null;
        String pendingTimestamp = null;

        try (BufferedReader reader = Files.newBufferedReader(subtitleFile.toPath(), StandardCharsets.UTF_8)) {
            String line;
            while ((line = reader.readLine()) != null) {
                if (line.trim().isEmpty()) {
                    continue;
                }

                if (line.matches("\\d{2}:\\d{2}:\\d{2}\\.\\d{3}\\s+-->\\s+\\d{2}:\\d{2}:\\d{2}\\.\\d{3}.*")) {
                    pendingTimestamp = cleanSubtitleLine(line);
                    continue;
                }

                if (line.contains("<c>") && line.contains("</c>")) {
                    isAutoGenerated = true;
                    // Extract and use the text from this line instead of skipping it
                    // This is important for YouTube Shorts which have word-level timestamps like:
                    // yo<00:00:01.280><c> your</c><00:00:01.480><c> place</c>
                    String extractedText = extractTextFromCTagLine(line);
                    if (!extractedText.isEmpty() && !StringUtils.equals(lastText, extractedText)) {
                        if (pendingTimestamp != null) {
                            subtitles.add(pendingTimestamp);
                            pendingTimestamp = null;
                        }
                        subtitles.add(extractedText);
                        lastText = extractedText;
                    }
                    continue;
                }

                String cleanedLine = cleanSubtitleLine(line);

                if (cleanedLine.isEmpty()) {
                    continue;
                }

                if (StringUtils.equals(lastText, cleanedLine)) {
                    continue;
                }

                if (pendingTimestamp != null) {
                    subtitles.add(pendingTimestamp);
                    pendingTimestamp = null;
                }

                subtitles.add(cleanedLine);
                lastText = cleanedLine;
            }
        }

        log.info("Subtitles content retrieved and cleaned. Is auto-generated: {}", isAutoGenerated);
        return new SubtitleAnalysisResult(subtitles, isAutoGenerated);
    }

    private String cleanSubtitleLine(String line) {
        String result = line;
        result = result.replaceAll("&nbsp;", "")
                .replaceAll("\\s+align:start position:0%$", "");

        result = result.replaceAll("\\s+", " ").trim();

        return result;
    }

    /**
     * Extract readable text from a line containing <c> tags with word-level timestamps.
     * Example input: yo<00:00:01.280><c> your</c><00:00:01.480><c> place</c><00:00:01.760><c> kind</c>
     * Expected output: yo your place kind
     */
    private String extractTextFromCTagLine(String line) {
        // Remove all inline timestamp tags like <00:00:01.280>
        String result = line.replaceAll("<\\d{2}:\\d{2}:\\d{2}\\.\\d{3}>", "");
        // Remove <c> and </c> tags
        result = result.replaceAll("</?c>", "");
        // Clean up extra whitespace
        result = result.replaceAll("\\s+", " ").trim();
        return result;
    }

    @Getter
    @AllArgsConstructor
    public static class SubtitleAnalysisResult {
        private final List<String> subtitles;
        private final boolean autoGenerated;
    }
}
